apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: sfox-rosetta-cardano
    stack: trading
  name: sfox-rosetta-cardano
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: sfox-rosetta-cardano
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "$ANNOTATION"
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9669'
      labels:
        k8s-app: sfox-rosetta-cardano
        stack: trading
      name: sfox-rosetta-cardano
    spec:
      containers:
      - image: 808678941459.dkr.ecr.us-east-1.amazonaws.com/cardano-rosetta:$IMAGE_TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 2000Mi
          limits:
            memory: 3000Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

